[package]
name = "lofty"
version = "0.1.1"
authors = ["Serial <69764315+Serial-ATA@users.noreply.github.com>", "Tianyi <ShiTianyi2001@outlook.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "Fork of https://github.com/TianyiShi2001/audiotags, adding support for more file types and (optionally) duration"
repository = "https://github.com/Serial-ATA/lofty-rs"
keywords = ["tags", "audio", "metadata"]
categories = ["accessibility", "multimedia::audio"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Ape
ape = {version = "0.3.0", optional = true}
# Wav
riff = {version = "1.0.1", optional = true}
# Mp3
id3 = {version = "0.6.3", optional = true} # De/Encoding
mp3-duration = {version = "0.1.10", optional = true} # Duration
# Ogg
lewton = {version = "0.10.2", optional = true} # Decoding
ogg = {version = "0.8.0", optional = true} # Encoding
# Mp4
mp4ameta = {version = "0.9.1", optional = true}
# Flac
metaflac = {version = "0.2.4", optional = true}
# Opus
opus_headers = {version = "0.1.2", optional = true}
# Errors
thiserror = "1.0.24"
byteorder = "1.4.3"
filepath = "0.1.1"

[features]
default = ["full"]
full = ["all_tags", "duration"]
mp4 = ["mp4ameta"]
flac = ["metaflac"]
opus = ["opus_headers"]
vorbis = ["lewton", "ogg"]
all_tags = ["vorbis", "opus", "flac", "mp4", "id3", "riff", "ape"]
duration = ["mp3-duration"]

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "read_from_extension"
harness = false

[[bench]]
name = "read_from_signature"
harness = false