[package]
name = "lofty"
version = "0.2.0"
authors = ["Serial <69764315+Serial-ATA@users.noreply.github.com>", "Tianyi <ShiTianyi2001@outlook.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "Unified IO for different types of audio metadata"
repository = "https://github.com/Serial-ATA/lofty-rs"
keywords = ["tags", "audio", "metadata"]
categories = ["accessibility", "multimedia::audio"]

[dependencies]
# Ape
ape = {version = "0.3.0", optional = true, git="https://github.com/rossnomann/rust-ape"}
# Riff
riff = {version = "1.0.1", optional = true}
# Id3
id3 = {version = "0.6.4", optional = true} # De/Encoding
filepath = { version = "0.1.1", optional = true } # wav/aiff only supports paths for some reason
# Mp3
mp3-duration = {version = "0.1.10", optional = true} # Duration
# Ogg
lewton = {version = "0.10.2", optional = true} # Decoding
ogg = {version = "0.8.0", optional = true} # Encoding
# Mp4
mp4ameta = {version = "0.10.2", optional = true}
# Flac
metaflac = {version = "0.2.4", optional = true}
# Errors
thiserror = "1.0.25"

base64 = "0.13.0"
byteorder = "1.4.3"

lofty_attr = "0.1.0"

[features]
default = ["full"]
full = ["all_tags", "duration"]
format-mp4 = ["mp4ameta"]
format-flac = ["metaflac"]
format-opus = []
format-vorbis = ["lewton", "ogg"]
format-ape = ["ape"]
format-id3 = ["id3", "filepath"]
format-riff = ["riff"]
format-ogg = ["format-flac", "format-opus", "format-vorbis"]
all_tags = ["format-ogg", "format-mp4", "format-id3", "format-riff", "format-ape"]
duration = ["mp3-duration"]

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "read_from_extension"
harness = false

[[bench]]
name = "read_from_signature"
harness = false