[package]
name = "lofty"
version = "0.1.0"
authors = ["Serial <69764315+Serial-ATA@users.noreply.github.com>", "Tianyi <ShiTianyi2001@outlook.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "Fork of https://github.com/TianyiShi2001/audiotags, adding support for more file types and (optionally) duration"
repository = "https://github.com/Serial-ATA/lofty-rs"
keywords = ["tags", "audio", "metadata"]
categories = ["accessiblity", "multimedia::audio"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opus_headers = {version = "0.1.2", optional = true}
lewton = {version = "0.10.2", optional = true}
mp4ameta = {version = "0.9.1", optional = true}
metaflac = {version = "0.2.4", optional = true}
ogg = {version = "0.8.0", optional = true}
id3 = {version = "0.6.2", optional = true}
mp3-duration = {version = "0.1.10", optional = true}
hound = {version = "3.4.0", optional = true}
thiserror = "1.0.24"

[features]
default = ["full"]
full = ["all_tags", "duration"]
mp4 = ["mp4ameta"]
mp3 = ["id3"]
wav = ["hound"]
vorbis = ["lewton", "metaflac", "opus_headers", "ogg"]
all_tags = ["vorbis", "mp4", "mp3", "wav"]
duration = ["mp3-duration"]