[package]
name = "lofty"
version = "0.3.0"
authors = ["Serial <69764315+Serial-ATA@users.noreply.github.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Audio metadata library"
repository = "https://github.com/Serial-ATA/lofty-rs"
keywords = ["tags", "audio", "metadata"]
categories = ["accessibility", "multimedia::audio"]

[dependencies]
# ID3 compressed frames
flate2 = { version = "1.0.21", optional = true }
# Vorbis comments pictures
base64 = { version = "0.13.0", optional = true }
# OGG Vorbis/Opus
ogg_pager = "0.1.7"
# Key maps
lazy_static = "1.4.0"
paste = "1.0.6"
byteorder = "1.4.3"

[features]
default = ["mp4_ilst", "vorbis_comments", "ape", "id3v1", "id3v2", "aiff_text_chunks", "riff_info_list"]
mp4_ilst = []
vorbis_comments = ["base64"]
ape = []
id3v1 = []
id3v2 = ["flate2"]
id3v2_restrictions = []
aiff_text_chunks = []
riff_info_list = []

[dev-dependencies]
criterion = { version = "0.3.5", features = ["html_reports"] }
tempfile = "3.2.0"
# tag_writer example
structopt = { version = "0.3.25", default-features = false }

[[bench]]
name = "read_file"
harness = false
