[package]
name = "lofty"
version = "0.3.0"
authors = ["Serial <69764315+Serial-ATA@users.noreply.github.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "Unified IO for different types of audio metadata"
repository = "https://github.com/Serial-ATA/lofty-rs"
keywords = ["tags", "audio", "metadata"]
categories = ["accessibility", "multimedia::audio"]

[dependencies]
# Id3
flate2 = { version = "1.0.21", optional = true }
# Ogg
ogg_pager = "0.1.7"
# Mp4
simdutf8 = { version = "0.1.3", optional = true }

# Quick string accessor methods for Tag
paste = { version = "1.0.5", optional = true }

base64 = "0.13.0"
byteorder = "1.4.3"

[features]
default = ["mp4_atoms", "vorbis_comments", "ape", "id3v1", "id3v2", "aiff_text_chunks", "riff_info_list", "quick_tag_accessors"]
mp4_atoms = ["simdutf8"]
vorbis_comments = []
ape = []
id3v1 = []
id3v2 = ["flate2"]
id3v2_restrictions = []
aiff_text_chunks = []
riff_info_list = []
quick_tag_accessors = ["paste"]

[dev-dependencies]
criterion = { version = "0.3.5", features = ["html_reports"] }

[[bench]]
name = "read_file"
harness = false
