[package]
name = "ogg_pager"
version = "0.1.1"
authors = ["Serial <69764315+Serial-ATA@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.4.3"